baseurl = "https://mv-photography.netlify.app/"
copyright = "Â© Matteo Valerio"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

theme = ["hugo-shortcode-gallery"]

[languages.en]

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 20

[[languages.en.menu.main]]
identifier = "camera-gear"
name = "Camera Gear"
url = "/camera-gear/"
weight = 30

[[languages.en.menu.main]]
identifier = "contacts"
name = "Contacts"
url = "/contacts/"
weight = 30

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.matteo-valerio]
default = true
name = "Matteo Valerio"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[params.paige]
color = "rgb(13, 110, 253)" # Bootstrap primary color and theme color for Safari and Windows

[params.paige.menu]
style = "underline" # Must be "links", "pills", "tabs", or "underline"